{
 "title": "Lab M07-01 — Diseño y links",
 "tags": [
  "lab",
  "example",
  "m07"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "node-exporter up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Business", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Revenue today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "title": "Navegación",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "options": {
    "content": "- [Lab M04-04 — Filtros región](/d/lab-m04-04)\n- [Lab M05-02 — Tablas](/d/lab-m05-02)\n- Tags: `lab`, `overview`, `m07`"
   }
  }
 ]
}