apiVersion: 1
datasources:
  - name: Prometheus-Provisioned
    uid: prometheus-provisioned
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      httpMethod: POST
